# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume_share', models.IntegerField()),
                ('volume_dollar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('yesterday', models.DateField()),
                ('is_rest_day', models.CharField(max_length=1)),
                ('weekday', models.CharField(max_length=1)),
                ('is_last_business_day_of_week', models.CharField(max_length=1)),
                ('is_last_business_day_of_month', models.CharField(max_length=1)),
                ('is_last_business_day_of_year', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DailyQuotes', to='api.TradingDay'),
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DailyQuotes', to='api.StockMaster'),
        ),
    ]
