# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaster',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
