# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161125_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquote',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='stockmaster',
            options={'ordering': ('code',)},
        ),
    ]
