# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161127_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyquote',
            old_name='end',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='dailyquote',
            old_name='start',
            new_name='open',
        ),
    ]
