# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161203_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquote',
            name='close',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='high',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='low',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='open',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='volume_dollar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='volume_share',
            field=models.BigIntegerField(),
        ),
    ]
