# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161205_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquote',
            options={'ordering': ('stock_id',)},
        ),
    ]
