# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161205_0313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='BaseInterest',
        ),
        migrations.RenameModel(
            old_name='BaseInterestRate',
            new_name='CurrencyRate',
        ),
        migrations.RenameField(
            model_name='baseinterest',
            old_name='rate',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='currencyrate',
            old_name='interest',
            new_name='rate',
        ),
    ]
