# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161205_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
